services:
  mysql:
    image: mysql:8
    container_name: levelup_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: level_up_store_db
    ports:
      - "3306:3306"
    volumes: 
      - mysql_data:/var/lib/mysql
    networks:
      - levelup-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: levelup_backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/level_up_store_db?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: create
      SPRING_SQL_INIT_MODE: never
    depends_on:
      - mysql
    networks:
      - levelup-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: levelup_frontend
    ports:
      - "80:80" # acceso p√∫blico
    networks:
      - levelup-network

volumes:
  mysql_data:

networks:
  levelup-network:
    driver: bridge
